# Top identity
title        : "Netra L. Prabhu"
name         : "Netra L. Prabhu"
description  : "Network Analysis, Bayesian Analysis, Machine Learning"
url          : "https://netra-prabhu.github.io"   # add quotes, no trailing slash
baseurl      : ""                                  # keep empty for user site
repository   : "netra-prabhu/netra-prabhu.github.io"   # <-- not academicpages

# Author (sidebar/profile)
author:
  avatar   : "/images/profile.jpg"     # put your file there
  name     : "Netra Prabhu"
  bio      : "PhD student in Statistics"
  location : "Raleigh, NC"
  email    : "nlprabhu@ncsu.edu"
  github   : "netra-prabhu"
  linkedin : "netra-prabhu-647a63133/"
  googlescholar: "https://scholar.google.com/citations?user=HCtwgPsAAAAJ&hl=en"
  orcid    : "https://orcid.org/my-orcid?orcid=0009-0005-5914-7642"   # optional, else delete line
  # remove all the other social keys you won't use to reduce clutter


# turn off unused collections to simplify
# (delete any existing 'collections:' block in your file)
# collections: {}

analytics:
  provider     : "false"

include:
  - _pages
  - files

markdown      : kramdown
highlighter   : rouge

defaults:
  - scope: { path: "", type: pages }
    values: { layout: single, author_profile: true }

sass: { sass_dir: _sass, style: compressed }
permalink: /:categories/:title/

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

compress_html:
  clippings: all
  ignore: { envs: development }
