# Top identity
title        : "Netra L. Prabhu"
name         : "Netra L. Prabhu"
description  : "Network Analysis, Bayesian Analysis, Machine Learning"
url          : "https://netra-prabhu.github.io"   # add quotes, no trailing slash
baseurl      : ""                                  # keep empty for user site
repository   : ""  # <-- not academicpages

# Author (sidebar/profile)
author:
  avatar   : "/images/profile.jpeg"     # put your file there
  name     : "Netra Prabhu"
  bio      : "PhD student in Statistics"
  location : "Raleigh, NC"
  email    : "nlprabhu@ncsu.edu"
  github   : "netra-prabhu"
  linkedin : "https://www.linkedin.com/in/netra-prabhu-647a63133/"
  googlescholar: "https://scholar.google.com/citations?user=HCtwgPsAAAAJ&hl=en"
  orcid    : "https://orcid.org/my-orcid?orcid=0009-0005-5914-7642"   # optional, else delete line
  # remove all the other social keys you won't use to reduce clutter
